#
#
#

#WIFI
WIFI_SSID_PQ = "X"
WIFI_PASS_PQ = "X"

WIFI_SSID_PR = "X"
WIFI_PASS_PR = "X"

WIFI_SSID_AL = "X"
WIFI_PASS_AL = "X"

WIFI_SSID = WIFI_SSID_PQ
WIFI_PASS = WIFI_PASS_PQ

#WIFI_SSID = WIFI_SSID_PR
#WIFI_PASS = WIFI_PASS_PR

#WIFI_SSID = WIFI_SSID_AL
#WIFI_PASS = WIFI_PASS_AL

#Telegram
TELEGRAM_API = "api.telegram.org"
TELEGRAM_PORT = 443
TELEGRAM_TOKEN = "X"
TELEGRAM_TIMEOUT = 3.0
TELEGRAM_URL = "https://" + TELEGRAM_API + "/bot" + TELEGRAM_TOKEN

#Somente funcionol com esta configuração
FIREBASE_HOST = "X"
FIREBASE_AUTH = "X"
FIREBASE_LED_STATUS = "LEDStatus"
FIREBASE_LAST_MESSAGE = "last_message"
FIREBASE_PORT = 80
FIREBASE_USERS = "users"
#FIREBASE_RFID_UID = "rfid_uid"

#Led
LED_PIN = 2 # D4
#ESP8266 logica barrada para o LED
LED_ON = 0 # LOW
LED_OFF = 1 # HIGH

